price:
  point:
    unit: 'P'
    color: '&e'
  token:
    unit: 'T'
    color: '&b'
  money:
    unit: '$'
    color: '&f'
bonus-lore:
- ''
- '&3Còn lại: &7%remain%/%limit%'
- '&3Giá: %priceColor%%priceValue%%priceUnit%'
- '&3Click trái: &7Xem'
- '&3Click phải: &7Mua'

hold-permission:
  vipcoin:
    permission: 'vipcoin.use'
    message: '&cSở hữu VIP trở lên để có thể dùng VIP Coin'

open-random:
  d1:
    c1:
      amount: 2
      items:
      - coal3
      - diamond3
      - gold3
      - iron3
    c2:
      amount: 3
      items:
        - lapis3
        - redstone3
        - oak3
        - darkoak3
        - birch3
        - wheat3
        - sugar3
    bonus:
      - lapis3
      - redstone3
      - oak3
      - darkoak3
      - birch3
      - wheat3
      - sugar3
      - coal3
      - diamond3
      - gold3
      - iron3